### PR TITLE
add docker-file

### PR DESCRIPTION
**Pull request by Joykoome**

### CODE REVIEW

**Comment by titusmuthomik** [comment]
hey

**Comment by titusmuthomik** [comment]
- Add a comprehensive PR description, refer to this [guide](https://talamobile.atlassian.net/wiki/spaces/ATLAS/pages/1096583374/Code+Review+Pull+Request+Guidelines) and this [template](https://github.com/inventure/Score_Threshold/blob/master/docs/pull_request_template.md)
- Rebase and squash your git commits into a more descriptive commit. Refer to this [guide](https://talamobile.atlassian.net/wiki/spaces/ATLAS/pages/2764898308/Git+Best+Practice+Rebasing+instead+of+Merging) for more info.

**Comment by Joykoome** [comment]
@titusmuthomik  Done. Please review it one more time

**Review by titusmuthomik — APPROVED** [review]
LGTM

**Pull request merged**
